<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/FileRead_REQUEST/types" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/REST/CallProcess_REQUEST/types" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" nssrcmpr ora oracle-xsl-mapper dvm oraext xsi xsd fn xp20 xsl ignore01 nsmpr0 nsmpr1 nsmpr2 nsmpr3 fn" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/adapter/REST/GetExtractedDataFromBucket_REQUEST/types" xmlns:nsmpr1="http://xmlns.oracle.com/cloud/adapter/REST/ProcessInvoice_REQUEST/types" xmlns:nsmpr2="http://xmlns.oracle.com/cloud/adapter/stagefile/ReadFile_REQUEST/types" xmlns:nsmpr3="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns37="http://xmlns.oracle.com/cloud/adapter/REST/CallProcess/types" xmlns:ns33="http://xmlns.oracle.com/cloud/adapter/stagefile/ReadFile/types">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_13/outbound_14/resourcegroup_15/FileRead_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/FileRead_REQUEST/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_139">
            <oracle-xsl-mapper:schema location="../../processor_81/resourcegroup_82/ReadFile_REQUEST.wsdl" xml:id="id_140"/>
            <oracle-xsl-mapper:rootElement name="ReadResponse" namespace="http://xmlns.oracle.com/cloud/adapter/stagefile/ReadFile_REQUEST/types" xml:id="id_141"/>
            <oracle-xsl-mapper:param name="ReadFile" xml:id="id_142"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_385/inbound_386/resourcegroup_387/CallProcess_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/CallProcess_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:param name="InvoiceDate" xml:id="id_39"/>
   <xsl:param name="InvoiceNumber" xml:id="id_40"/>
   <xsl:param name="InvoiceTotal" xml:id="id_41"/>
   <xsl:param name="VendorName" xml:id="id_47"/>
   <xsl:param name="ReadFile" xml:id="id_152"/>
   <xsl:param name="SupplierSite" xml:id="id_229"/>
   <xsl:param name="InvoiceTrackingID" xml:id="id_257"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:execute xml:id="id_12">
         <ns37:request-wrapper xml:id="id_52">
            <ns37:params xml:id="id_53">
               <ns37:applicationName xml:id="id_54">
                  <xsl:value-of xml:id="id_55" select="&quot;IDPExceptionApp&quot;"/>
               </ns37:applicationName>
               <ns37:processName xml:id="id_56">
                  <xsl:value-of xml:id="id_57" select="&quot;InvoiceExceptionProcess&quot;"/>
               </ns37:processName>
            </ns37:params>
            <ns37:dataObject xml:id="id_58">
               <ns37:invoiceDetails xml:id="id_59">
                  <ns37:invoiceNumber xml:id="id_110">
                     <xsl:value-of xml:id="id_111" select="$InvoiceNumber"/>
                  </ns37:invoiceNumber>
                  <ns37:invoiceCurrency xml:id="id_112">
                     <xsl:value-of xml:id="id_113" select="&quot;USD&quot;"/>
                  </ns37:invoiceCurrency>
                  <ns37:invoiceAmount xml:id="id_116">
                     <xsl:value-of xml:id="id_117" select="$InvoiceTotal"/>
                  </ns37:invoiceAmount>
                  <ns37:invoiceDate xml:id="id_108">
                     <xsl:value-of xml:id="id_109" select="$InvoiceDate"/>
                  </ns37:invoiceDate>
                  <ns37:businessUnit xml:id="id_121">
                     <xsl:value-of xml:id="id_122" select="&quot;US1 Business Unit&quot;"/>
                  </ns37:businessUnit>
                  <ns37:supplier xml:id="id_114">
                     <xsl:value-of xml:id="id_118" select="$VendorName"/>
                  </ns37:supplier>
                  <ns37:supplierSite xml:id="id_119">
                     <xsl:value-of xml:id="id_234" select="$SupplierSite"/>
                  </ns37:supplierSite>
               <ns37:invoiceGroup xml:id="id_199">
                     <xsl:value-of xml:id="id_200" select="&quot;Supplier Group&quot;"/>
                  </ns37:invoiceGroup>
                  <ns37:description xml:id="id_201">
                     <xsl:value-of xml:id="id_202" select="&quot;Descriptipon&quot;"/>
                  </ns37:description>
                  <xsl:for-each xml:id="id_159" select="$ReadFile/nsmpr2:ReadResponse/ns33:request-wrapper/ns33:pages/ns33:documentFields/ns33:fieldValue/ns33:items">
                     <ns37:invoiceLines xml:id="id_160">
                        <ns37:item xml:id="id_324">
                           <xsl:value-of xml:id="id_325" select="ns33:fieldValue/ns33:items[ns33:fieldLabel/ns33:name=&quot;Description&quot;]/ns33:fieldValue/ns33:value"/>
                        </ns37:item>
                        <ns37:lineNumber xml:id="id_161">
                           <xsl:value-of xml:id="id_167" select="position ()"/>
                        </ns37:lineNumber>
                        <ns37:lineAmount xml:id="id_162">
                           <xsl:value-of xml:id="id_168" select="ns33:fieldValue/ns33:items[ns33:fieldLabel/ns33:name=&quot;Amount&quot;]/ns33:fieldValue/ns33:value"/>
                        </ns37:lineAmount>
                        <ns37:accountingDate xml:id="id_163">
                           <xsl:value-of xml:id="id_166" select="$InvoiceDate"/>
                        </ns37:accountingDate>
                        <ns37:distributionCombination xml:id="id_164">
                           <xsl:value-of xml:id="id_165" select="&quot;101.10.65600.121.000.000&quot;"/>
                        </ns37:distributionCombination>
                     </ns37:invoiceLines>
                  </xsl:for-each>
               <ns37:id xml:id="id_294">
                     <xsl:value-of xml:id="id_295" select="$InvoiceTrackingID"/>
                  </ns37:id>
               </ns37:invoiceDetails>
            </ns37:dataObject>
         </ns37:request-wrapper>
      </nstrgmpr:execute>
   </xsl:template>
</xsl:stylesheet>