<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/FileRead_REQUEST/types" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/collocatedics/UpdateStatusWaitingForApporval_REQUEST/types" exclude-result-prefixes=" nssrcmpr ora oracle-xsl-mapper dvm oraext xsi xsd fn xp20 xsl ignore01 nsmpr0 nsmpr1 nsmpr2 nsmpr3 nsmpr4 nsmpr5" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/adapter/REST/CallProcess_REQUEST/types" xmlns:nsmpr1="http://xmlns.oracle.com/cloud/adapter/REST/GetExtractedDataFromBucket_REQUEST/types" xmlns:nsmpr2="http://xmlns.oracle.com/cloud/adapter/REST/ProcessInvoice_REQUEST/types" xmlns:nsmpr3="http://xmlns.oracle.com/cloud/adapter/stagefile/ReadFile_REQUEST/types" xmlns:nsmpr4="http://xmlns.oracle.com/cloud/adapter/collocatedics/UploadDocumentToProcessTask_REQUEST/types" xmlns:nsmpr5="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns47="http://www.oracle.rest.converters.autogeneratedns.com/collocatedics/UpdateStatusWaitingForApporval_REQUEST">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_13/outbound_14/resourcegroup_15/FileRead_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/FileRead_REQUEST/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_458/inbound_459/resourcegroup_460/UpdateStatusWaitingForApporval_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="POST" namespace="http://xmlns.oracle.com/cloud/adapter/collocatedics/UpdateStatusWaitingForApporval_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:param name="InvoiceDate" xml:id="id_57"/>
   <xsl:param name="InvoiceNumber" xml:id="id_58"/>
   <xsl:param name="InvoiceTotal" xml:id="id_59"/>
   <xsl:param name="InvoiceTrackingID" xml:id="id_60"/>
   <xsl:param name="VendorName" xml:id="id_67"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:POST xml:id="id_12">
         <nstrgmpr:components.schemas.request-wrapper xml:id="id_72">
            <ns47:ID xml:id="id_73">
               <xsl:value-of xml:id="id_77" select="$InvoiceTrackingID"/>
            </ns47:ID>
            <ns47:InvoiceNumber xml:id="id_75">
               <xsl:value-of xml:id="id_76" select="$InvoiceNumber"/>
            </ns47:InvoiceNumber>
            <ns47:Source xml:id="id_82">
               <xsl:value-of xml:id="id_83" select="&quot;Outlook&quot;"/>
            </ns47:Source>
            <ns47:InvoiceTotal xml:id="id_80">
               <xsl:value-of xml:id="id_81" select="$InvoiceTotal"/>
            </ns47:InvoiceTotal>
            <ns47:InvoiceDate xml:id="id_78">
               <xsl:value-of xml:id="id_79" select="$InvoiceDate"/>
            </ns47:InvoiceDate>
            <ns47:InvoiceCurrency xml:id="id_84">
               <xsl:value-of xml:id="id_85" select="&quot;USD&quot;"/>
            </ns47:InvoiceCurrency>
            <ns47:Supplier xml:id="id_86">
               <xsl:value-of xml:id="id_87" select="$VendorName"/>
            </ns47:Supplier>
            <ns47:Status xml:id="id_88">
               <xsl:value-of xml:id="id_89" select="&quot;Waiting For Approval&quot;"/>
            </ns47:Status>
         <ns47:LastUpdateDateTime xml:id="id_144">
               <xsl:value-of xml:id="id_145" select="fn:current-dateTime ()"/>
            </ns47:LastUpdateDateTime>
         </nstrgmpr:components.schemas.request-wrapper>
      </nstrgmpr:POST>
   </xsl:template>
</xsl:stylesheet>