<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/UpdateStatus_REQUEST/types" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/REST/InsertRecord_REQUEST/types" exclude-result-prefixes=" ora oracle-xsl-mapper dvm oraext xsi xsd fn xp20 nssrcmpr xsl ignore01 nsmpr0 nsmpr1" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns23="http://xmlns.oracle.com/cloud/adapter/REST/InsertRecord/types" xmlns:ns19="http://xmlns.oracle.com/cloud/adapter/REST/UpdateStatus/types" xmlns:nsmpr1="http://xmlns.oracle.com/cloud/adapter/REST/GetAllRecords_REQUEST/types">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_13/outbound_14/resourcegroup_15/UpdateStatus_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/UpdateStatus_REQUEST/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_36/inbound_37/resourcegroup_38/InsertRecord_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/InsertRecord_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:execute xml:id="id_12">
         <ns23:request-wrapper xml:id="id_21">
            <ns23:invoiceID xml:id="id_60">
               <xsl:value-of xml:id="id_61" select="/nssrcmpr:execute/ns19:request-wrapper/ns19:ID"/>
            </ns23:invoiceID>
            <ns23:invoiceNumber xml:id="id_22">
               <xsl:value-of xml:id="id_23" select="/nssrcmpr:execute/ns19:request-wrapper/ns19:InvoiceNumber"/>
            </ns23:invoiceNumber>
            <ns23:source xml:id="id_24">
               <xsl:value-of xml:id="id_25" select="/nssrcmpr:execute/ns19:request-wrapper/ns19:Source"/>
            </ns23:source>
            <ns23:invoiceTotal xml:id="id_26">
               <xsl:value-of xml:id="id_27" select="/nssrcmpr:execute/ns19:request-wrapper/ns19:InvoiceTotal"/>
            </ns23:invoiceTotal>
            <ns23:invoiceDate xml:id="id_28">
               <xsl:value-of xml:id="id_29" select="/nssrcmpr:execute/ns19:request-wrapper/ns19:InvoiceDate"/>
            </ns23:invoiceDate>
            <ns23:invoiceCurrency xml:id="id_30">
               <xsl:value-of xml:id="id_31" select="/nssrcmpr:execute/ns19:request-wrapper/ns19:InvoiceCurrency"/>
            </ns23:invoiceCurrency>
            <ns23:supplier xml:id="id_32">
               <xsl:value-of xml:id="id_33" select="/nssrcmpr:execute/ns19:request-wrapper/ns19:Supplier"/>
            </ns23:supplier>
            <ns23:status xml:id="id_34">
               <xsl:value-of xml:id="id_35" select="/nssrcmpr:execute/ns19:request-wrapper/ns19:Status"/>
            </ns23:status>
            <ns23:invoiceAssignee xml:id="id_36">
               <xsl:value-of xml:id="id_37" select="/nssrcmpr:execute/ns19:request-wrapper/ns19:InvoiceAssignee"/>
            </ns23:invoiceAssignee>
            <ns23:lastUpdateDateTime xml:id="id_38">
               <xsl:value-of xml:id="id_39" select="/nssrcmpr:execute/ns19:request-wrapper/ns19:LastUpdateDateTime"/>
            </ns23:lastUpdateDateTime>
         </ns23:request-wrapper>
      </nstrgmpr:execute>
   </xsl:template>
</xsl:stylesheet>