<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:nssrcmpr="http://www.oracle.com/2014/03/ics/schedule" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/collocatedics/CallIntegrationToExtractData_REQUEST/types" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" nssrcmpr ora oracle-xsl-mapper dvm oraext xsi xsd fn xp20 xsl ignore01 nsmpr0 nsmpr1 nsmpr2 nsmpr3 oraext" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/adapter/microsoftemail/GetAttachments/types" xmlns:nsmpr1="http://xmlns.oracle.com/cloud/adapter/microsoftemail/GetMessages/types" xmlns:nsmpr2="http://xmlns.oracle.com/cloud/adapter/microsoftemail/GetEachAttachment/types" xmlns:nsmpr3="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns24="http://xmlns.oracle.com/cloud/ics/binary/v1/types" xmlns:ns27="http://xmlns.oracle.com/cloud/openapi/cloudobject/collocatedics/CallIntegrationToExtractData_REQUEST">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="XSD" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../processor_8/resourcegroup_9/ICSSchedule_1.xsd" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="schedule" namespace="http://www.oracle.com/2014/03/ics/schedule" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_13">
            <oracle-xsl-mapper:schema location="../../processor_100/resourcegroup_124/generated.wsdl" xml:id="id_14"/>
            <oracle-xsl-mapper:rootElement name="value" namespace="http://xmlns.oracle.com/cloud/adapter/microsoftemail/GetAttachments/types" xml:id="id_15"/>
            <oracle-xsl-mapper:param name="CurrentAttachment" xml:id="id_16"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_203/inbound_204/resourcegroup_205/CallIntegrationToExtractData_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="POST" namespace="http://xmlns.oracle.com/cloud/adapter/collocatedics/CallIntegrationToExtractData_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:param name="CurrentAttachment" xml:id="id_49"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:POST xml:id="id_12">
         <nstrgmpr:QueryParameters xml:id="id_106">
            </nstrgmpr:QueryParameters>
         <ns24:streamReference xml:id="id_61">
            <xsl:value-of xml:id="id_62" select="oraext:decodeBase64ToReference ($CurrentAttachment/nsmpr0:value/nsmpr0:contentBytes )"/>
         </ns24:streamReference>
      </nstrgmpr:POST>
   </xsl:template>
</xsl:stylesheet>