<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/FileRead_REQUEST/types" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/REST/ProcessInvoice_REQUEST/types" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" nssrcmpr ora oracle-xsl-mapper dvm oraext xsi xsd fn xp20 xsl ignore01 nsmpr0 oraext nsmpr1" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns22="http://xmlns.oracle.com/cloud/adapter/REST/ProcessInvoice/types" xmlns:ns15="http://xmlns.oracle.com/cloud/ics/binary/v1/types" xmlns:nsmpr1="http://www.oracle.rest.converters.autogeneratedns.com/collocatedics/CallERPUpdate_REQUEST">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_13/outbound_14/resourcegroup_15/FileRead_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/FileRead_REQUEST/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_20/inbound_21/resourcegroup_22/ProcessInvoice_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/ProcessInvoice_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:execute xml:id="id_12">
         <ns22:request-wrapper xml:id="id_21">
            <ns22:processorConfig xml:id="id_22">
               <ns22:processorType xml:id="id_23">
                  <xsl:value-of xml:id="id_24" select="&quot;GENERAL&quot;"/>
               </ns22:processorType>
               <ns22:language xml:id="id_25">
                  <xsl:value-of xml:id="id_26" select="&quot;ENG&quot;"/>
               </ns22:language>
               <ns22:isZipOutputEnabled xml:id="id_57">
                  <xsl:value-of xml:id="id_58" select="&quot;false&quot;"/>
               </ns22:isZipOutputEnabled>
               <ns22:features xml:id="id_27">
                  <ns22:featureType xml:id="id_28">
                     <xsl:value-of xml:id="id_29" select="&quot;KEY_VALUE_EXTRACTION&quot;"/>
                  </ns22:featureType>
               </ns22:features>
            <ns22:features xml:id="id_27">
                  <ns22:featureType xml:id="id_60">
                     <xsl:value-of xml:id="id_61" select="&quot;DOCUMENT_CLASSIFICATION&quot;"/>
                  </ns22:featureType>
                  <ns22:maxResults xml:id="id_62">
                     <xsl:value-of xml:id="id_63" select="5"/>
                  </ns22:maxResults>
               </ns22:features>
            </ns22:processorConfig>
            <ns22:inputLocation xml:id="id_30">
               <ns22:sourceType xml:id="id_31">
                  <xsl:value-of xml:id="id_32" select="&quot;INLINE_DOCUMENT_CONTENT&quot;"/>
               </ns22:sourceType>
               <ns22:data xml:id="id_33">
                  <xsl:value-of xml:id="id_34" select="oraext:encodeReferenceToBase64 (/nssrcmpr:execute/ns15:streamReference )"/>
               </ns22:data>
            </ns22:inputLocation>
            <ns22:compartmentId xml:id="id_42">
               <xsl:value-of xml:id="id_43" select="&quot;ocid1.compartment.oc1..aaaaaaaakcuk5bslbaiyc72m2je27zyvqlfrny6wt56ojr5s6uwa5kuxb4na&quot;"/>
            </ns22:compartmentId>
            <ns22:outputLocation xml:id="id_35">
               <ns22:namespaceName xml:id="id_36">
                  <xsl:value-of xml:id="id_37" select="&quot;orasenatdpltintegration01&quot;"/>
               </ns22:namespaceName>
               <ns22:bucketName xml:id="id_38">
                  <xsl:value-of xml:id="id_39" select="&quot;oic-demo&quot;"/>
               </ns22:bucketName>
               <ns22:prefix xml:id="id_40">
                  <xsl:value-of xml:id="id_41" select="&quot;Invoice&quot;"/>
               </ns22:prefix>
            </ns22:outputLocation>
         </ns22:request-wrapper>
      </nstrgmpr:execute>
   </xsl:template>
</xsl:stylesheet>