<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/FileRead_REQUEST/types" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/collocatedics/UploadDocumentToProcessTask_REQUEST/types" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" nssrcmpr ora oracle-xsl-mapper dvm oraext xsi xsd fn xp20 xsl ignore01 nsmpr0 nsmpr1 nsmpr2 nsmpr3 nsmpr4 fn" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/adapter/REST/CallProcess_REQUEST/types" xmlns:nsmpr1="http://xmlns.oracle.com/cloud/adapter/REST/GetExtractedDataFromBucket_REQUEST/types" xmlns:nsmpr2="http://xmlns.oracle.com/cloud/adapter/REST/ProcessInvoice_REQUEST/types" xmlns:nsmpr3="http://xmlns.oracle.com/cloud/adapter/stagefile/ReadFile_REQUEST/types" xmlns:nsmpr4="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns19="http://xmlns.oracle.com/cloud/ics/binary/v1/types" xmlns:ns43="http://xmlns.oracle.com/cloud/openapi/cloudobject/collocatedics/UploadDocumentToProcessTask_REQUEST" xmlns:ns27="http://xmlns.oracle.com/cloud/adapter/REST/CallProcess/types">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../application_13/outbound_14/resourcegroup_15/FileRead_REQUEST.wsdl" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/FileRead_REQUEST/types" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_64">
            <oracle-xsl-mapper:schema location="../../application_385/inbound_386/resourcegroup_387/CallProcess_REQUEST.wsdl" xml:id="id_65"/>
            <oracle-xsl-mapper:rootElement name="executeResponse" namespace="http://xmlns.oracle.com/cloud/adapter/REST/CallProcess_REQUEST/types" xml:id="id_66"/>
            <oracle-xsl-mapper:param name="CallProcess" xml:id="id_67"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_122">
            <oracle-xsl-mapper:schema location="../../application_385/inbound_386/resourcegroup_387/CallProcess_REQUEST.wsdl" xml:id="id_123"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/CallProcess_REQUEST/types" xml:id="id_124"/>
            <oracle-xsl-mapper:param name="CallProcess_REQUEST" xml:id="id_125"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_126">
            <oracle-xsl-mapper:schema location="../../application_37/inbound_38/resourcegroup_39/GetExtractedDataFromBucket_REQUEST.wsdl" xml:id="id_127"/>
            <oracle-xsl-mapper:rootElement name="executeResponse" namespace="http://xmlns.oracle.com/cloud/adapter/REST/GetExtractedDataFromBucket_REQUEST/types" xml:id="id_128"/>
            <oracle-xsl-mapper:param name="GetExtractedDataFromBucket" xml:id="id_129"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_130">
            <oracle-xsl-mapper:schema location="../../application_37/inbound_38/resourcegroup_39/GetExtractedDataFromBucket_REQUEST.wsdl" xml:id="id_131"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/GetExtractedDataFromBucket_REQUEST/types" xml:id="id_132"/>
            <oracle-xsl-mapper:param name="GetExtractedDataFromBucket_REQUEST" xml:id="id_133"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_134">
            <oracle-xsl-mapper:schema location="../../application_20/inbound_21/resourcegroup_22/ProcessInvoice_REQUEST.wsdl" xml:id="id_135"/>
            <oracle-xsl-mapper:rootElement name="executeResponse" namespace="http://xmlns.oracle.com/cloud/adapter/REST/ProcessInvoice_REQUEST/types" xml:id="id_136"/>
            <oracle-xsl-mapper:param name="ProcessInvoice" xml:id="id_137"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_138">
            <oracle-xsl-mapper:schema location="../../application_20/inbound_21/resourcegroup_22/ProcessInvoice_REQUEST.wsdl" xml:id="id_139"/>
            <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/ProcessInvoice_REQUEST/types" xml:id="id_140"/>
            <oracle-xsl-mapper:param name="ProcessInvoice_REQUEST" xml:id="id_141"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_142">
            <oracle-xsl-mapper:schema location="../../processor_81/resourcegroup_82/ReadFile_REQUEST.wsdl" xml:id="id_143"/>
            <oracle-xsl-mapper:rootElement name="ReadResponse" namespace="http://xmlns.oracle.com/cloud/adapter/stagefile/ReadFile_REQUEST/types" xml:id="id_144"/>
            <oracle-xsl-mapper:param name="ReadFile" xml:id="id_145"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD" xml:id="id_146">
            <oracle-xsl-mapper:schema location="../../processor_1/resourcegroup_2/ICSIntegrationMetadata.xsd" xml:id="id_147"/>
            <oracle-xsl-mapper:rootElement name="metadata" namespace="http://www.oracle.com/2014/03/ic/integration/metadata" xml:id="id_148"/>
            <oracle-xsl-mapper:param name="self" xml:id="id_149"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_404/inbound_405/resourcegroup_406/UploadDocumentToProcessTask_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="POST" namespace="http://xmlns.oracle.com/cloud/adapter/collocatedics/UploadDocumentToProcessTask_REQUEST/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:param name="CallProcess" xml:id="id_96"/>
   <xsl:param name="InvoiceNumber" xml:id="id_101"/>
   <xsl:param name="CallProcess_REQUEST" xml:id="id_150"/>
   <xsl:param name="GetExtractedDataFromBucket" xml:id="id_151"/>
   <xsl:param name="GetExtractedDataFromBucket_REQUEST" xml:id="id_152"/>
   <xsl:param name="InvoiceDate" xml:id="id_153"/>
   <xsl:param name="InvoiceTotal" xml:id="id_154"/>
   <xsl:param name="ProcessInvoice" xml:id="id_155"/>
   <xsl:param name="ProcessInvoice_REQUEST" xml:id="id_156"/>
   <xsl:param name="ReadFile" xml:id="id_158"/>
   <xsl:param name="VendorName" xml:id="id_160"/>
   <xsl:param name="self" xml:id="id_161"/>
   <xsl:param name="tracking_var_1" xml:id="id_162"/>
   <xsl:param name="tracking_var_2" xml:id="id_163"/>
   <xsl:param name="tracking_var_3" xml:id="id_164"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:POST xml:id="id_12">
         <nstrgmpr:QueryParameters xml:id="id_113">
            <ns43:processInstanceId xml:id="id_120">
               <xsl:value-of xml:id="id_121" select="$CallProcess/nsmpr0:executeResponse/ns27:response-wrapper/ns27:id"/>
            </ns43:processInstanceId>
            <ns43:fileName xml:id="id_114">
               <xsl:value-of xml:id="id_115" select="concat ($InvoiceNumber, &quot;.pdf&quot; )"/>
            </ns43:fileName>
            <ns43:documentName xml:id="id_116">
               <xsl:value-of xml:id="id_117" select="concat ($InvoiceNumber, &quot;.pdf&quot; )"/>
            </ns43:documentName>
            <ns43:contentType xml:id="id_118">
               <xsl:value-of xml:id="id_119" select="&quot;application/pdf&quot;"/>
            </ns43:contentType>
         </nstrgmpr:QueryParameters>
         <ns19:streamReference xml:id="id_62">
            <xsl:value-of xml:id="id_63" select="/nssrcmpr:execute/ns19:streamReference"/>
         </ns19:streamReference>
      </nstrgmpr:POST>
   </xsl:template>
</xsl:stylesheet>