<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/erp/CreateInvoice_REQUEST/types" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:nssrcmpr="http://xmlns.oracle.com/cloud/adapter/REST/UpdateInvoice_REQUEST/types" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" xmlns:nsmpr0="http://www.oracle.com/2014/03/ic/integration/metadata" xmlns:ns27="http://xmlns.oracle.com/cloud/adapters/fscmRestApp" xmlns:ns22="http://xmlns.oracle.com/cloud/adapter/REST/UpdateInvoice/types" xmlns:ns25="http://xmlns.oracle.com/cloud/adapters/fscmRestApp/Invoices" version="2.0" xml:id="id_1" exclude-result-prefixes=" ora nssrcmpr oracle-xsl-mapper dvm oraext xsi xsd fn xp20 xsl ignore01 nsmpr0" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace">
        <oracle-xsl-mapper:schema xml:id="id_2">
              <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
              <oracle-xsl-mapper:mapSources xml:id="id_3">
                    <oracle-xsl-mapper:source type="WSDL" xml:id="id_4">
                          <oracle-xsl-mapper:schema location="../../application_13/outbound_14/resourcegroup_15/UpdateInvoice_REQUEST.wsdl" xml:id="id_5"/>
                          <oracle-xsl-mapper:rootElement name="execute" namespace="http://xmlns.oracle.com/cloud/adapter/REST/UpdateInvoice_REQUEST/types" xml:id="id_6"/>
                    </oracle-xsl-mapper:source>
              </oracle-xsl-mapper:mapSources>
              <oracle-xsl-mapper:mapTargets xml:id="id_7">
                    <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
                          <oracle-xsl-mapper:schema location="../../application_30/inbound_31/resourcegroup_32/CreateInvoice_REQUEST.wsdl" xml:id="id_9"/>
                          <oracle-xsl-mapper:rootElement name="create" namespace="http://xmlns.oracle.com/cloud/adapter/erp/CreateInvoice_REQUEST/types" xml:id="id_10"/>
                    </oracle-xsl-mapper:target>
              </oracle-xsl-mapper:mapTargets>
        </oracle-xsl-mapper:schema>
        <xsl:template match="/" xml:id="id_11">
              <nstrgmpr:create xml:id="id_12">
                    <nstrgmpr:Invoices xml:id="id_21">
                          <ns27:InvoiceNumber xml:id="id_22">
                                <xsl:value-of xml:id="id_23" select="/nssrcmpr:execute/ns22:request-wrapper/ns22:InvoiceNumber"/>
                          </ns27:InvoiceNumber>
                          <ns27:InvoiceCurrency xml:id="id_24">
                                <xsl:value-of xml:id="id_25" select="/nssrcmpr:execute/ns22:request-wrapper/ns22:InvoiceCurrency"/>
                          </ns27:InvoiceCurrency>
                          <ns27:InvoiceAmount xml:id="id_26">
                                <xsl:value-of xml:id="id_27" select="/nssrcmpr:execute/ns22:request-wrapper/ns22:InvoiceAmount"/>
                          </ns27:InvoiceAmount>
                          <ns27:InvoiceDate xml:id="id_28">
                                <xsl:value-of xml:id="id_29" select="/nssrcmpr:execute/ns22:request-wrapper/ns22:InvoiceDate"/>
                          </ns27:InvoiceDate>
                          <ns27:BusinessUnit xml:id="id_30">
                                <xsl:value-of xml:id="id_31" select="/nssrcmpr:execute/ns22:request-wrapper/ns22:BusinessUnit"/>
                          </ns27:BusinessUnit>
                          <ns27:Supplier xml:id="id_34">
                                <xsl:value-of xml:id="id_35" select="/nssrcmpr:execute/ns22:request-wrapper/ns22:Supplier"/>
                          </ns27:Supplier>
                          <ns27:SupplierSite xml:id="id_32">
                                <xsl:value-of xml:id="id_33" select="/nssrcmpr:execute/ns22:request-wrapper/ns22:SupplierSite"/>
                          </ns27:SupplierSite>
                          <ns27:InvoiceGroup xml:id="id_36">
                                <xsl:value-of xml:id="id_37" select="/nssrcmpr:execute/ns22:request-wrapper/ns22:InvoiceGroup"/>
                          </ns27:InvoiceGroup>
                          <ns27:Description xml:id="id_38">
                                <xsl:value-of xml:id="id_39" select="/nssrcmpr:execute/ns22:request-wrapper/ns22:Description"/>
                          </ns27:Description>
                          <xsl:for-each select="/nssrcmpr:execute/ns22:request-wrapper/ns22:invoiceLines">
                                <ns27:invoiceLines xml:id="id_40">
                                      <ns25:LineNumber xml:id="id_41">
                                            <xsl:value-of xml:id="id_42" select="ns22:LineNumber"/>
                                      </ns25:LineNumber>
                                      <ns25:LineAmount xml:id="id_43">
                                            <xsl:value-of xml:id="id_44" select="ns22:LineAmount"/>
                                      </ns25:LineAmount>
                                      <ns25:AccountingDate xml:id="id_45">
                                            <xsl:value-of xml:id="id_46" select="ns22:AccountingDate"/>
                                      </ns25:AccountingDate>
                                      <ns25:DistributionCombination xml:id="id_47">
                                            <xsl:value-of xml:id="id_48" select="ns22:DistributionCombination"/>
                                      </ns25:DistributionCombination>
                                </ns27:invoiceLines>
                          </xsl:for-each>
                    </nstrgmpr:Invoices>
              </nstrgmpr:create>
        </xsl:template>
  </xsl:stylesheet>