<?xml version = '1.0' encoding = 'UTF-8'?>
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE-->
<!--User Editing Not Allowed for Sections: oracle-xsl-mapper:schema, top level xsl:params, version attribute of the stylesheet element. GENERATED BY OIC MAPPER, DO NOT DELETE THIS LINE--><xsl:stylesheet version="2.0" xml:id="id_1" xmlns:nssrcmpr="http://www.oracle.com/2014/03/ics/schedule" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:nstrgmpr="http://xmlns.oracle.com/cloud/adapter/microsoftemail/GetEachAttachment/types" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" nssrcmpr ora oracle-xsl-mapper dvm oraext xsi xsd fn xp20 xsl ignore01 nsmpr0 nsmpr1 nsmpr2" xmlns:ignore01="http://www.oracle.com/XSL/Transform/java" ignore01:ignorexmlids="true" xmlns:xml="http://www.w3.org/XML/1998/namespace" xmlns:nsmpr0="http://xmlns.oracle.com/cloud/adapter/microsoftemail/GetAttachments/types" xmlns:nsmpr1="http://xmlns.oracle.com/cloud/adapter/microsoftemail/GetMessages/types" xmlns:nsmpr2="http://www.oracle.com/2014/03/ic/integration/metadata">
   <oracle-xsl-mapper:schema xml:id="id_2">
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources xml:id="id_3">
         <oracle-xsl-mapper:source type="XSD" xml:id="id_4">
            <oracle-xsl-mapper:schema location="../../processor_8/resourcegroup_9/ICSSchedule_1.xsd" xml:id="id_5"/>
            <oracle-xsl-mapper:rootElement name="schedule" namespace="http://www.oracle.com/2014/03/ics/schedule" xml:id="id_6"/>
         </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="WSDL" xml:id="id_13">
            <oracle-xsl-mapper:schema location="../../processor_100/resourcegroup_124/generated.wsdl" xml:id="id_14"/>
            <oracle-xsl-mapper:rootElement name="value" namespace="http://xmlns.oracle.com/cloud/adapter/microsoftemail/GetAttachments/types" xml:id="id_15"/>
            <oracle-xsl-mapper:param name="CurrentAttachment" xml:id="id_16"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL" xml:id="id_17">
            <oracle-xsl-mapper:schema location="../../processor_35/resourcegroup_42/generated.wsdl" xml:id="id_18"/>
            <oracle-xsl-mapper:rootElement name="value" namespace="http://xmlns.oracle.com/cloud/adapter/microsoftemail/GetMessages/types" xml:id="id_19"/>
            <oracle-xsl-mapper:param name="CurrentEmail" xml:id="id_20"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets xml:id="id_7">
         <oracle-xsl-mapper:target type="WSDL" xml:id="id_8">
            <oracle-xsl-mapper:schema location="../../application_130/inbound_131/resourcegroup_132/GetEachAttachment_REQUEST.wsdl" xml:id="id_9"/>
            <oracle-xsl-mapper:rootElement name="Get-Message-Attachment-Graph-API_GET" namespace="http://xmlns.oracle.com/cloud/adapter/microsoftemail/GetEachAttachment/types" xml:id="id_10"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
   </oracle-xsl-mapper:schema>
   <xsl:param name="CurrentAttachment" xml:id="id_41"/>
   <xsl:param name="CurrentEmail" xml:id="id_42"/>
   <xsl:template match="/" xml:id="id_11">
      <nstrgmpr:Get-Message-Attachment-Graph-API_GET xml:id="id_12">
         <nstrgmpr:TemplateParameters xml:id="id_51">
            <nstrgmpr:message_id xml:id="id_54">
               <xsl:value-of xml:id="id_55" select="$CurrentEmail/nsmpr1:value/nsmpr1:id"/>
            </nstrgmpr:message_id>
            <nstrgmpr:attachment_id xml:id="id_52">
               <xsl:value-of xml:id="id_53" select="$CurrentAttachment/nsmpr0:value/nsmpr0:id"/>
            </nstrgmpr:attachment_id>
         </nstrgmpr:TemplateParameters>
      </nstrgmpr:Get-Message-Attachment-Graph-API_GET>
   </xsl:template>
</xsl:stylesheet>